GET http://localhost:3000/usuarios/

###
GET http://localhost:3000/login

###
POST http://localhost:3000/11010287931
Content-Type: application/json

{
        "nome": "Natanael Toniazzo",
        "funcao": "Auxiliar de qualidade",
        "cpf": 11010287931,
        "email": "natanael.toniazzo@gmail.com",
        "telefone": 49998293621,
        "isAdmin": true
}

###
DELETE http://localhost:3000/usuarios/11010287931

###
PATCH http://localhost:3000/usuarios/123123
Content-Type: application/json

{
    "nome": "Natanael Atualizado"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "natanael.toniazzo@gmail.com",
    "password": "123456"
}