GET http://localhost:3000/usuarios

###
GET http://localhost:3000/usuarios/11010287931

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
        "nome": "Natanael Toniazzo",
        "funcao": "Auxiliar de qualidade",
        "cpf": 11010287931,
        "email": "natanael.toniazzo@gmail.com",
        "senha": "123456",
        "telefone": 49998293621,
        "isAdmin": true
}

###
DELETE http://localhost:3000/usuarios/605cde9f41dbc823ecc82647

###
PATCH http://localhost:3000/usuarios/605cdd52c0afa808e0ec4204
Content-Type: application/json

{
    "nome": "Natanael Atualizado"
}