GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlzQWRtaW4iOnRydWUsIl9pZCI6IjYwNWYyN2ZhYjg5MDQ5MTQ1MGU4NjZiZSIsIm5vbWUiOiJOYXRhbmFlbCBUb25pYXp6byIsImZ1bmNhbyI6IkF1eGlsaWFyIGRlIHF1YWxpZGFkZSIsImNwZiI6MTEwMTAyODc5MzEsImVtYWlsIjoibmF0YW5hZWwudG9uaWF6em9AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkNU9Fb1VKcGJzNHNJQjVoQ2NnMmhIT3luYnAzT21hT2llUFZSZHpiLnRicXBpNGZVVGVRdG0iLCJ0ZWxlZm9uZSI6NDk5OTgyOTM2MjEsIl9fdiI6MH0sImlhdCI6MTYxNzA0NjQyMH0.hAYbImG34ZD-8-YDkOGTZZMcR8lmAgzKX_1NS4xSKCM

###
GET http://localhost:3000/login

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
        "nome": "Natanael Toniazzo",
        "funcao": "Auxiliar de qualidade",
        "cpf": 11010287931,
        "email": "natanael.toniazzo@gmail.com",
        "password": "123456",
        "telefone": 49998293621,
        "isAdmin": true
}

###
DELETE http://localhost:3000/usuarios/605e430f50995d2b10b18919

###
PATCH http://localhost:3000/usuarios/605cdd52c0afa808e0ec4204
Content-Type: application/json

{
    "nome": "Natanael Atualizado"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "natanael.toniazzo@gmail.com",
    "password": "123456"
}